it("First Test: Generate Line Chart", function () {
    cy.visit("/")
    cy.findByRole("link", { name: "Line" }).click()
    cy.get('[id="chart-title-input"]').type("Cats Vs Dogs")
    cy.get('[id="x-label-input"]').type("Cats")
    cy.get('[id="y-label-input"]').type("Dogs")
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="x_input"]').eq(0).type(1)
    cy.get('[id="x_input"]').eq(1).type(2)
    cy.get('[id="x_input"]').eq(2).type(3)
    cy.get('[id="x_input"]').eq(3).type(4)
    cy.get('[id="x_input"]').eq(4).type(5)
    cy.get('[id="y_input"]').eq(0).type(3)
    cy.get('[id="y_input"]').eq(1).type(7)
    cy.get('[id="y_input"]').eq(2).type(15)
    cy.get('[id="y_input"]').eq(3).type(25)
    cy.get('[id="y_input"]').eq(4).type(40)
    cy.get('[id="chart-color-input"]').invoke('val', '#891F1F').trigger('change')
    cy.get('[id="generate-chart-btn"]').click()
    cy.get('[id="chart-img"]').should("exist")
})

it("First Test: Generate Bar Chart", function () {
    cy.visit("/")
    cy.findByRole("link", { name: "Bar" }).click()
    cy.get('[id="chart-title-input"]').type("Cats Vs Dogs")
    cy.get('[id="x-label-input"]').type("Cats")
    cy.get('[id="y-label-input"]').type("Dogs")
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="x_input"]').eq(0).type(1)
    cy.get('[id="x_input"]').eq(1).type(2)
    cy.get('[id="x_input"]').eq(2).type(3)
    cy.get('[id="x_input"]').eq(3).type(4)
    cy.get('[id="x_input"]').eq(4).type(5)
    cy.get('[id="y_input"]').eq(0).type(3)
    cy.get('[id="y_input"]').eq(1).type(7)
    cy.get('[id="y_input"]').eq(2).type(15)
    cy.get('[id="y_input"]').eq(3).type(25)
    cy.get('[id="y_input"]').eq(4).type(40)
    cy.get('[id="chart-color-input"]').invoke('val', '#891F1F').trigger('change')
    cy.get('[id="generate-chart-btn"]').click()
    cy.get('[id="chart-img"]').should("exist")
})

it("First Test: Generate Scatter Chart", function () {
    cy.visit("/")
    cy.findByRole("link", { name: "Scatter" }).click()
    cy.get('[id="chart-title-input"]').type("Cats Vs Dogs")
    cy.get('[id="x-label-input"]').type("Cats")
    cy.get('[id="y-label-input"]').type("Dogs")
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="x_input"]').eq(0).type(1)
    cy.get('[id="x_input"]').eq(1).type(2)
    cy.get('[id="x_input"]').eq(2).type(3)
    cy.get('[id="x_input"]').eq(3).type(4)
    cy.get('[id="x_input"]').eq(4).type(5)
    cy.get('[id="y_input"]').eq(0).type(3)
    cy.get('[id="y_input"]').eq(1).type(7)
    cy.get('[id="y_input"]').eq(2).type(15)
    cy.get('[id="y_input"]').eq(3).type(25)
    cy.get('[id="y_input"]').eq(4).type(40)
    cy.get('[id="chart-color-input"]').invoke('val', '#891F1F').trigger('change')
    cy.get('[id="generate-chart-btn"]').click()
    cy.get('[id="chart-img"]').should("exist")
})

it("Second Test: Moving Between Pages", function () {
    cy.visit("/")
    cy.findByRole("link", { name: "Line" }).click()
    cy.get('[id="chart-title-input"]').type("Cats Vs Dogs")
    cy.get('[id="x-label-input"]').type("Cats")
    cy.get('[id="y-label-input"]').type("Dogs")
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="x_input"]').eq(0).type(1)
    cy.get('[id="x_input"]').eq(1).type(2)
    cy.get('[id="x_input"]').eq(2).type(3)
    cy.get('[id="x_input"]').eq(3).type(4)
    cy.get('[id="x_input"]').eq(4).type(5)
    cy.get('[id="y_input"]').eq(0).type(3)
    cy.get('[id="y_input"]').eq(1).type(7)
    cy.get('[id="y_input"]').eq(2).type(15)
    cy.get('[id="y_input"]').eq(3).type(25)
    cy.get('[id="y_input"]').eq(4).type(40)
    cy.get('[id="chart-color-input"]').invoke('val', '#891F1F').trigger('change')
    cy.get('[id="generate-chart-btn"]').click()
    cy.get('[id="chart-img"]').should("exist")
    cy.findByRole("link", { name: "Scatter" }).click()
    cy.get('[id="chart-title-input"]').should('have.value', "Cats Vs Dogs")
    cy.get('[id="x-label-input"]').should('have.value', "Cats")
    cy.get('[id="y-label-input"]').should('have.value', "Dogs")
    cy.get('[id="x_input"]').eq(0).should('have.value', 1)
    cy.get('[id="x_input"]').eq(1).should('have.value', 2)
    cy.get('[id="x_input"]').eq(2).should('have.value', 3)
    cy.get('[id="x_input"]').eq(3).should('have.value', 4)
    cy.get('[id="x_input"]').eq(4).should('have.value', 5)
    cy.get('[id="y_input"]').eq(0).should('have.value', 3)
    cy.get('[id="y_input"]').eq(1).should('have.value', 7)
    cy.get('[id="y_input"]').eq(2).should('have.value', 15)
    cy.get('[id="y_input"]').eq(3).should('have.value', 25)
    cy.get('[id="y_input"]').eq(4).should('have.value', 40)
    cy.findByRole("link", { name: "Bar" }).click()
    cy.get('[id="chart-title-input"]').should('have.value', "Cats Vs Dogs")
    cy.get('[id="x-label-input"]').should('have.value', "Cats")
    cy.get('[id="y-label-input"]').should('have.value', "Dogs")
    cy.get('[id="x_input"]').eq(0).should('have.value', 1)
    cy.get('[id="x_input"]').eq(1).should('have.value', 2)
    cy.get('[id="x_input"]').eq(2).should('have.value', 3)
    cy.get('[id="x_input"]').eq(3).should('have.value', 4)
    cy.get('[id="x_input"]').eq(4).should('have.value', 5)
    cy.get('[id="y_input"]').eq(0).should('have.value', 3)
    cy.get('[id="y_input"]').eq(1).should('have.value', 7)
    cy.get('[id="y_input"]').eq(2).should('have.value', 15)
    cy.get('[id="y_input"]').eq(3).should('have.value', 25)
    cy.get('[id="y_input"]').eq(4).should('have.value', 40)

})


it("Third Test: Save Chart", function () {
    cy.visit("/")
    cy.findByRole("link", { name: "Line" }).click()
    cy.get('[id="chart-title-input"]').type("Cats Vs Dogs")
    cy.get('[id="x-label-input"]').type("Cats")
    cy.get('[id="y-label-input"]').type("Dogs")
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="x_input"]').eq(0).type(1)
    cy.get('[id="x_input"]').eq(1).type(2)
    cy.get('[id="x_input"]').eq(2).type(3)
    cy.get('[id="x_input"]').eq(3).type(4)
    cy.get('[id="x_input"]').eq(4).type(5)
    cy.get('[id="y_input"]').eq(0).type(3)
    cy.get('[id="y_input"]').eq(1).type(7)
    cy.get('[id="y_input"]').eq(2).type(15)
    cy.get('[id="y_input"]').eq(3).type(25)
    cy.get('[id="y_input"]').eq(4).type(40)
    cy.get('[id="chart-color-input"]').invoke('val', '#891F1F').trigger('change')
    cy.get('[id="generate-chart-btn"]').click()
    cy.get('[id="chart-img"]').should("exist")
    cy.get('[id="save-chart-btn"]').should("have.not.value","disabled").click()
    cy.findByRole("link", { name: "Gallery" }).click()
    cy.findByText("Cats Vs Dogs").should("exist")


})

it("Fourth Test: Open Saved Chart", function () {
    cy.visit("/")
    cy.findByRole("link", { name: "Line" }).click()
    cy.get('[id="chart-title-input"]').type("Cats Vs Dogs")
    cy.get('[id="x-label-input"]').type("Cats")
    cy.get('[id="y-label-input"]').type("Dogs")
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="add-values-btn"]').click()
    cy.get('[id="x_input"]').eq(0).type(1)
    cy.get('[id="x_input"]').eq(1).type(2)
    cy.get('[id="x_input"]').eq(2).type(3)
    cy.get('[id="x_input"]').eq(3).type(4)
    cy.get('[id="x_input"]').eq(4).type(5)
    cy.get('[id="y_input"]').eq(0).type(3)
    cy.get('[id="y_input"]').eq(1).type(7)
    cy.get('[id="y_input"]').eq(2).type(15)
    cy.get('[id="y_input"]').eq(3).type(25)
    cy.get('[id="y_input"]').eq(4).type(40)
    cy.get('[id="chart-color-input"]').invoke('val', '#891F1F').trigger('change')
    cy.get('[id="generate-chart-btn"]').click()
    cy.get('[id="chart-img"]').should("exist")
    cy.get('[id="save-chart-btn"]').should("have.not.value","disabled").click()
    cy.findByRole("link", { name: "Gallery" }).click()
    cy.findByText("Cats Vs Dogs").should("exist")
    cy.get('.chart-img').click()
    cy.get('[id="chart-title-input"]').should('have.value', "Cats Vs Dogs")
    cy.get('[id="x-label-input"]').should('have.value', "Cats")
    cy.get('[id="y-label-input"]').should('have.value', "Dogs")
    cy.get('[id="x_input"]').eq(0).should('have.value', 1)
    cy.get('[id="x_input"]').eq(1).should('have.value', 2)
    cy.get('[id="x_input"]').eq(2).should('have.value', 3)
    cy.get('[id="x_input"]').eq(3).should('have.value', 4)
    cy.get('[id="x_input"]').eq(4).should('have.value', 5)
    cy.get('[id="y_input"]').eq(0).should('have.value', 3)
    cy.get('[id="y_input"]').eq(1).should('have.value', 7)
    cy.get('[id="y_input"]').eq(2).should('have.value', 15)
    cy.get('[id="y_input"]').eq(3).should('have.value', 25)
    cy.get('[id="y_input"]').eq(4).should('have.value', 40)
})
